# How I scraped international SERPs using the Serpstack API

## 1. I imported Pandas and found a Gist of countries and country codes on GitHub

In [1]:
import pandas as pd

csv = 'https://gist.githubusercontent.com/tadast/8827699/raw/f5cac3d42d16b78348610fc4ec301e9234f82821/countries_codes_and_coordinates.csv'

csv_df = pd.read_csv(csv)

csv_df

,Country,Alpha-2 code,Alpha-3 code,Numeric code,Latitude (average),Longitude (average)
0,Afghanistan,"""AF""","""AFG""","""4""","""33""","""65"""
1,Albania,"""AL""","""ALB""","""8""","""41""","""20"""
2,Algeria,"""DZ""","""DZA""","""12""","""28""","""3"""
3,American Samoa,"""AS""","""ASM""","""16""","""-14.3333""","""-170"""
4,Andorra,"""AD""","""AND""","""20""","""42.5""","""1.6"""
...,...,...,...,...,...,...
251,Wallis and Futuna,"""WF""","""WLF""","""876""","""-13.3""","""-176.2"""
252,Western Sahara,"""EH""","""ESH""","""732""","""24.5""","""-13"""
253,Yemen,"""YE""","""YEM""","""887""","""15""","""48"""
254,Zambia,"""ZM""","""ZMB""","""894""","""-15""","""30"""
255,Zimbabwe,"""ZW""","""ZWE""","""716""","""-20""","""30"""

## 2. Then I set up my list of countries, filtered out all the countries not in my list, and turned it into a list. I also reformatted it as it had double quotes already in it which I didn't want

In [2]:
my_country_list = list({"Russia", "Germany", "France", "United Kingdom", "Italy", "Spain", "Ukraine", "Poland", "Romania", "Netherlands", "Belgium", "Greece", "Portugal", "Czech Republic", "Hungary", "Sweden", "Belarus", "Austria", "Switzerland", "Bulgaria", "Serbia", "Denmark", "Finland", "Slovakia", "Norway", "Ireland", "Croatia", "Bosnia and Herzegovina", "Moldova", "Lithuania", "Albania", "Macedonia", "Slovenia", "Latvia", "Kosovo", "Estonia", "Montenegro", "Luxembourg", "Malta", "Iceland", "Andorra", "Liechtenstein", "Monaco", "Vietnam", "China", "Afghanistan", "Armenia", "Azerbaijan", "Bahrain", "Bangladesh", "Bhutan", "Brunei", "Cambodia", "China (PRC)", "East Timor", "Georgia", "Hong Kong", "India", "Indonesia", "Iran", "Iraq", "Israel", "Japan", "Jordan", "Kazakhstan", "Kuwait", "Kyrgyzstan", "Laos", "Lebanon", "Macau", "Malaysia", "Maldives", "Mongolia", "Myanmar", "Nepal", "North Korea", "Oman", "Pakistan", "Palestine", "Qatar", "Russia", "Saudi Arabia", "Singapore", "South Korea", "Sri Lanka", "Syria", "Taiwan", "Tajikistan", "Thailand", "The Philippines", "Turkey", "Turkmenistan", "United Arab Emirates", "Uzbekistan", "Vietnam", "Yemen"})

new_csv_df = csv_df[csv_df['Country'].isin(my_country_list)].reset_index()

my_country_code_list = new_csv_df['Alpha-2 code'].to_list()

my_country_code_list = [i.replace(' "', '').replace('"','') for i in my_country_code_list]

my_country_code_list

['AF',
 'AL',
 'AD',
 'AM',
 'AT',
 'AZ',
 'BH',
 'BD',
 'BY',
 'BE',
 'BT',
 'BA',
 'BN',
 'BG',
 'KH',
 'CN',
 'HR',
 'CZ',
 'DK',
 'EE',
 'FI',
 'FR',
 'GE',
 'DE',
 'GR',
 'HK',
 'HU',
 'IS',
 'IN',
 'ID',
 'IQ',
 'IE',
 'IL',
 'IT',
 'JP',
 'JO',
 'KZ',
 'KR',
 'KW',
 'KG',
 'LV',
 'LB',
 'LI',
 'LT',
 'LU',
 'MY',
 'MV',
 'MT',
 'MC',
 'MN',
 'ME',
 'MM',
 'NP',
 'NL',
 'NO',
 'OM',
 'PK',
 'PL',
 'PT',
 'QA',
 'RO',
 'RU',
 'SA',
 'RS',
 'SG',
 'SK',
 'SI',
 'ES',
 'LK',
 'SE',
 'CH',
 'TW',
 'TJ',
 'TH',
 'TR',
 'TM',
 'UA',
 'AE',
 'GB',
 'UZ',
 'VN',
 'YE']

## 3. Finally, I ran a for-loop that iterated through each country code from the list, and completed a search in that given country. I then ran another for-loop to iterate through each SERP result and printed out the country code and link found in position 1

**_Note: I used print() as it was easier to copy and paste into a spreadsheet but you can turn the result into a list and export as a CSV if necessary._**

In [ ]:
for c in my_country_code_list:

    params = {
        'access_key': 'ACCESS KEY',
        'query': 'KEYWORD',
        'gl': c
    }

    api_result = requests.get('http://api.serpstack.com/search', params, verify=False)

    api_response = api_result.json()

    org = api_response.get("organic_results")
    
    for results in range(0,len(org)):
        if org[results]['position'] == 1:
            print(f"{c}\t{org[results]['url']}")